// Standard Purchase Order Terms & Conditions (Appendix A) - reproduced
// verbatim from the organisation's existing PO template at the user's
// request, so the in-app generator carries the same legal terms, just in
// our own layout.
export const PO_TERMS_INTRO = "The purchase order from NLF is subject to the following terms and conditions:"

export const PO_TERMS_CLAUSES = [
  "Vendor/Service Provider represents that it is qualified, competent, authorized, and not barred, under applicable law(s), its charter documents, and any contracts that it may have entered into with a third party, to enter into this purchase/service order and ensure its performance in accordance with the terms contained herein. It further represents that it is not subject to any liquidation/insolvency/winding-up proceeding at the behest of a third-party or volitionally, is not being investigated by any regulator, and has all permits, licenses, registrations as may be necessary under applicable laws and is compliant with all applicable law for the purposes of performing its business and operations, including this purchase/service order.",
  "Vendor/Service Provider agrees and acknowledges that the consideration received from NLF has been received against the provision of goods/services to NLF under this purchase/service order.",
  "Vendor/Service Provider shall conduct itself in a timely, diligent, and professional manner, exhibiting prudent business decisions and always on an arm's- length basis while performing the purchase/service orders.",
  "Vendor/Service Provider may hire and engage personnel, staff, employees, consultants, and other contracting parties as required who have the requisite skill, know-how, experience, expertise and qualification to fulfil the performance under the purchase/service order, subject to any other condition that is specifically stated for contracting parties in this Appendix A. Vendor/Service Provider shall at all times be responsible for actions or omissions of its personnel, staff, employees, consultants and other contracting parties, and this liability is without any exception whatsoever.",
  "Alongside, Vendor/Service Provider shall at all times during the performance and tenure of the purchase/service order ensure compliance with all applicable laws.",
  "Notwithstanding contained anywhere else, Vendor/Service Provider shall not change any terms or any details provided in the purchase/service order without the prior written consent of NLF, failing which NLF shall have the right to seek refund of the already disbursed amounts of consideration, or suspend the purchase/service order, or terminate the purchase/service order, at its sole discretion. This is without prejudice to NLF's right to seek appropriate relief under law, contract, and equity.",
  "Vendor/Service Provider shall be responsible for all warehousing, logistics, supply chain and distribution aspects connected with purchase/service order, unless otherwise agreed between the parties in an e- mail, written document, or a contract/agreement.",
  "During the implementation of the purchase/service order, Vendor/Service Provider shall provide regular updates on progress made, hindrances encountered, other relevant information that will enable NLF to ensure compliance with the terms herein.",
  "Time is of essence for the purposes of the purchase/service order, and Vendor/Service Provider shall strictly comply with the timelines mandated by NLF, unless agreed otherwise in writing between the parties.",
  "NLF shall have the right to require the Vendor/Service Provider to provide details related to the performance of this Purchase/Service Order such as sub-contracts executed, sub-vendors used for performance, details of personnel/employees engaged, invoices raised, delivery documents, no-objections and permits obtained, tax filings completed, proof of payment of goods/services tax and customs duty (if any), due diligence conducted on contracting parties, proposals received, insurances obtained, real time update on transit, background information on workability and utility of assets/equipment/material/supplies/services, warranty certificates, certificates and documents from original equipment manufacturer, and other such documents as may be required by NLF (Documents). Vendor/Service Provider shall cooperate and without demur provide Documents within 5 days from the date on which NLF raises the request for Documents.",
  "Vendor/Service Provider authorizes NLF to share information/Documents/reports provided to NLF to its representatives, donors and their representatives, as well as on social media, publications, press releases, or any other physical/digital medium. NLF shall, in such process, exercise reasonable care to ensure that price-sensitive information as identified by Vendor/Service Provider is maintained as confidential. The information/Documents/reports obtained from Vendor/Service Provider may be used for any of the following purposes: (i) to assess impact of the charitable activities carried out or funded by NLF; or (ii) audit and evaluate the Vendor/Service Provider by NLF and/or its donors; or (iii) ensure the Vendor/Service Provider's compliance with applicable law or any other contract/agreement that NLF is bound by, and for other promotional/public relation/business development purposes.",
  "Each party is responsible for its taxes under applicable law.",
  "Vendor/Service Provider acknowledges that NLF is a not-for-profit entity registered under Section 8 of the Indian Companies Act, 2013, and as such consideration is provided by NLF out of charitable contributions made by its donors, and as such a breach of these terms or applicable law can lead to reputational damage and adverse consequences for NLF, and in such instances, NLF in addition to remedies under contract, shall have the right to seek suitable relief under applicable law and/or equity.",
  "The consideration shall be disbursed through a bank transfer to the bank account designated by the Vendor/Service Provider. If nothing is mentioned or agreed, it is understood that Vendor/Service Provider shall raise a draft invoice, and NLF shall have a right to review and require suitable revisions to the draft invoice within 7 days from the date on which the draft invoice is provided. The draft invoice must state the all-inclusive consideration, including all taxes, transportation charges etc. Suggested revisions or clarifications must be provided by the Vendor/Service Provider within 7 days on the date on which it receives the revision or queries from NLF. Final invoices shall be payable within 30 business days from the date on which the final invoice is accepted in writing by NLF. It is clarified that where amounts have been paid as advance towards the consideration, Vendor/Service Provider shall provide detailed explanation and accounts on how the advance has been used, before any draft invoice is raised for further consideration payments.",
  "In the circumstance that the consideration cannot be disbursed as per agreed timelines due to circumstances beyond reasonable control of the Parties including but not limited to banking holidays, change in law, internet and cyber security incident, pandemic, epidemic, riots, curfew, emergency, civil strife, elections, lockdowns, quarantine restrictions, declared disasters, acts of God and other such circumstances, there shall be no default on part of NLF, and the Vendor/Service Provider shall not be entitled to suspend performance or terminate the purchase/service order.",
  "If required, Vendor/Service Provider shall require its contracting parties and all representatives including employees, staff, officers, directors and other personnel, whether there is a written contract or not, to sign and provide such undertakings/declarations/letters as required by NLF for the purposes of (i) compliance with applicable law, (ii) absence of any third-party claim with respect to breach of confidentiality obligations that it may be exposed to as well as breach of any intellectual property rights, (iii) absence of corruption and money-laundering practices. This clause shall survive the term of the purchase/service order for a period of 1 year.",
  "While dealing or handling with the equipment/material/assets/supplies/services, Vendor/Service Provider shall exercise all care and diligence that it does for its own assets and Vendor/Service Provider further acknowledges that such care is essential for implementation of the purchase/service order.",
  "Further, the Vendor/Service Provider shall not provide possession or allow use of the equipment/material/assets/supplies/services to any other organization or person, without prior consent of NLF.",
  "Vendor/Service Provider shall not directly or indirectly engage in activities that are or can be construed as political lobbying, acting as agents in government tenders, making political contributions in cash or kind, affiliation to any political, religious or other sectarian ideologies and practices, money laundering activities, dealing and transacting with entities/individuals/association of people sanctioned/blacklisted/being investigated by Indian government, the Office of Foreign Assets Control (United States of America), the Interpol, United Nations and its organisations and/or any government intelligence agency.",
  "Vendor/Service Provider shall pro-actively notify NLF of any potential or actual breach of these terms or applicable law by itself or by its directors, members, officers, employees, staff, personnel, agent or any other representative and ensure that its representatives comply with the terms herein.",
  "Vendor/Service Provider shall maintain adequate infrastructure including any other equipment, supplies, logistics arrangement, and other facilities for performing the purchase/service order.",
  "Vendor/Service Provider shall not use NLF's logo, mark, note, content, design, tradename, trade dress, brand, copyrightable material, domain name, knowhow, or any other proprietary information contained in digital or physical medium that belongs to or is provided by NLF in any manner, except with prior written consent from NLF. This clause shall survive the purchase/service order.",
  "Vendor/Service Provider shall maintain all information provided by NLF (written or oral) including terms of this purchase/service order confidential, and not disclose it to any third-party or use it any other manner except for performance of this Agreement. This clause shall survive the purchase/service order.",
  "Vendor/Service Provider undertakes to comply with applicable anti-corruption and anti-money laundering laws as provided in Appendix B.",
  "Vendor/Service Provider shall not use, engage or contract with an agent, consultant, contractor or other third party to perform any of its obligations under this Agreement without notifying NLF in writing. Vendor/Service provider shall be absolutely and solely responsible for actions and omissions of such contracting party at all times and this liability is without any exception whatsoever.",
  "Vendor/Service Provider warrants that the assets/supplies/equipment/device/implements/serv ices provided are fit for use and purpose, qualitative, not in breach of any third-party's proprietary or intellectual property rights, can be delivered/performed and availed by NLF, free from any latent or patent defect, usable, in good condition, in conformity with applicable laws, fit for use or consumption at the time of delivery/provision and for such other extended period as specified in the purchase/service order. This clause shall survive the purchase/service order.",
  "NLF shall not be responsible in any form or manner for breach of applicable law, terms contained herein, representations made, warranties provided, timeline for performance, which shall be the sole and absolute liability of the Vendor/Service Provider.",
  "Vendor/Service Provider shall indemnify, defend, and hold NLF and its affiliates, partners, collaborating entities, employees, directors, officers, agents, advisors, and other representatives harmless from and against any losses, claims, suits, damages, liabilities, penalties, interests, fines, costs and expenses (including legal fees and reasonable attorneys' fees) based upon, arising in whole or in part, directly or indirectly, from the acts or omissions, or alleged acts or omissions of Vendor/Service Provider and/or its listed representatives, or third party claims attributable to the conduct of Vendor/Service Provider and/or its representatives including any claim for breach of intellectual property, warranty breach, compensation claims for harm caused to any person, corrupt practices, material misrepresentation, and fraud. It is clarified herein that the indemnification obligation herein shall include any claims by third parties for injunctive relief, compensatory damages, harassment complaints and attorneys' fees for misappropriation of trade secrets, breach of personal data related rights, privacy, intellectual property, product liability claims, or any similar claims. It is further clarified that indemnity shall not be the sole monetary remedy for the NLF, who shall at its discretion choose to avail for any other remedy under applicable law or equity.",
  "NLF shall have the right to terminate the purchase/service order with 30 days' notice to Vendor/Service Provider, except where NLF decides to terminate the purchase/service order for any (i) default or breach of Vendor/Service Provider, which is not remedied within 10 days of being notified by NLF; or (ii) breach of applicable law by Vendor/Service Provider; or (iii) bankruptcy or winding-up proceedings are initiated against the Service Provider, or a liquidator is appointed on its assets, in which case, NLF shall have not obligation to make any payments or provide any notice whatsoever.",
  "Upon termination for any cause whatsoever, Vendor/Service Provider shall (i) provide all other documents/information as is specifically required by NLF under these terms, (ii) immediately return any tangible or intangible property that belongs to or is owned by NLF, (iii) destroy any confidential information or proprietary information belonging to or owned by NLF with written confirmation about the same. All of these actions will be performed within 7 days from the date of termination.",
  "Vendor/Service Provider represents that it is fully conversant with the requirements under these laws and further represents that it or its officers, directors, employees, staff, personnel, agents, advisors, and other representatives are not in breach of the requirements under these laws.",
  "NLF's liability shall be limited to only direct losses incurred by the Vendor/Service Provider for actions or omissions of NLF. No liability whatsoever shall be incurred for indirect, consequential, exemplary, special, punitive losses/damages, loss of profits, loss of business, loss of reputation, loss of life/limb, loss of goodwill, breach of trust, equitable reliefs, and contingent or conditional liability of any kind.",
  "Any amendment, modification, alteration, change, addition or deletion in to the purchase/service order shall be done by mutual consent of the Parties in writing and such amendment, modification, alteration, change, addition or deletion shall form part of this purchase/service order.",
  "Applicable law shall be Indian laws, and all disputes shall be attempted to be resolved through negotiations between the Parties. If such negotiations remain unsuccessful within 30 days of commencement of negotiations, then, the dispute shall be subjected to court adjudication with competent courts in Bengaluru, Karnataka.",
]
